# Vite React Frontend Service
services:
  country-trivia-react:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: country-trivia-react
    restart: unless-stopped
    ports:
      - "5000:80"
